package com.olklein.choreo.syllabus;

/**
 * Created by olklein on 24/10/2017.
 */

public class chacha {
    public static final String[][] FIGURESTEMPOLIST = {
            {"TIME STEP",                   "2 3 4 &1 2 3 4&1",
                                                    "Start: RF closed to LF (Close Opp. w/o Hold hold)\nFinish: LF to side (Close Opp. w/o Hold)"},
            {"CLOSE BASIC MOVEMENT",        "2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd T turned out (Close Opp. Normal Hold)\nFinish: RF to side (Close Opp. Normal Hold)"},
            {"OPEN BASIC MOVEMENT",         "2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd T turned out (Open Opp. LH to RH)\nFinish: RF fwd (Open Opp. LH to RH)"},
            {"NEW YORK TO R",               "2 3 4&1",
                                                    "Start: LF fwd and across body, T turned out (L Side Same, LH to RH)\nFinish: LF to side (Open Opp. LH to RH)"},
            {"NEW YORK TO L",               "2 3 4&1",
                                                    "Start: RF fwd and across body, T turned out (R Side Same, RH to LH)\nFinish: RF to side (Open Opp. RH to LH)"},
            {"HAND TO HAND TO R",           "2 3 4&1",
                                                    "Start: RF bwd (L Side Same, LH to RH)\nFinish: RF to side (Open Opp. LH to RH)"},
            {"HAND TO HAND TO L",           "2 3 4&1",
                                                    "Start: LF bwd (R Side Same, RH to LH)\nFinish: LF to side (Open Opp. RH to LH)"},
            {"SPOT TURN TO R",              "2 3 4&1",
                                                    "Start: LF fwd and slightly across the body (L Side Same, Release Hold)\nFinish: LF to side (Open Opp. LH to RH)"},
            {"SPOT TURN TO L",              "2 3 4&1",
                                                    "Start: RF fwd and slightly across the body (R Side Same, Release Hold)\nFinish: RF to side (Open Opp. RH to LH)"},
            {"UNDERARM TURN TURNING R",     "2 3 4&1",
                                                    "Start: RF bwd (L Diag. R Angle, Lady turns under Man’s LH)\nFinish: RF to side (Close Opp. Normal Hold)"},
            {"UNDERARM TURN TURNING L",     "2 3 4&1",
                                                    "Start: LF fwd T turned out (L Diag. Same, Lady turns under Man’s LH)\nFinish: LF to side (Close Opp. Normal Hold)"},
            {"THREE CHA CHA CHAS TO R",     "4&1 2&3 4&1",
                                                    "Start: RF to side (Open Opp. LH to RH)\nFinish: RF to side (Open Opp. LH to RH)"},
            {"THREE CHA CHA CHAS TO L",     "4&1 2&3 4&1",
                                                    "Start: LF to side (Open Opp. RH to LH)\nFinish: LF to side (Open Opp. RH to LH)"},
            {"SHOULDER TO SHOULDER",        "2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd OP, T turned out (L Diag. Opp. w/o Hold)\nFinish: RF to side (Open Opp. w/o Hold)"},
            {"AIDA",                        "2 3 4&1 2 3 4&1 2 3 4&1",
                                                    "Start: RF bwd (L Side Same, LH to RH)\nFinish: RF to side (Open Opp. LH to RH)"},
            {"FAN",                         "2 3 4&1",
                                                    "Start: RF bwd (L Diag. R Angle, RH releases Hold)\nFinish: RF to side (fan L Angle, LH to RH)"},
            {"OPEN HIP TWIST",              "2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd, T turned out (Open Opp. LH to RH)\nFinish: RF to side (Fan L Angle, LH to RH)"},
            {"OPEN HIP TWIST TO CHASSE",    "2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd, T turned out (Open Opp. LH to RH)\nFinish: RF to side (Back R Diag Same. Normal Hold)"},
            {"CLOSE HIP TWIST",             "2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd T turned out (Close Opp. Normal Hold)\nFinish: RF to side (Fan L Angle, LH to RH)"},
            {"CLOSE HIP TWIST TO CHASSE",   "2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd T turned out (Close Opp. Normal Hold)\nFinish: RF to side (Open Opp. LH to RH)"},
            {"HOCKEY STICK",                "2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd T turned out (Fan L Angle, LH to RH)\nFinish: RF fwd (Open Opp. LH to RH)"},
            {"HOCKEY STICK TO CHASSE",      "2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd T turned out (Fan L Angle, LH to RH)\nFinish: RF to side (Open Opp. LH to RH)"},
            {"ALEMANA",                     "2 3 4&1 2 3 4&.1",
                                                    "Start: LF fwd, T turned out (Fan L Angle, LH to RH)\nFinish: RF fwd and slightly across the body (R Diag. Opp. Normal Hold)"},
            {"ALEMANA FROM OPEN OPP. POS.", "2 3 4&1 2 3 4&.1.",
                                                    "Start: LF fwd, T turned out (Open Opp. LH to RH)\nFinish: RF fwd and slightly across the body (R Diag Opp. Normal Hold)"},
            {"NATURAL TOP",                 "2 3 4&1 2 3 4&1 2 3 4&1",
                                                    "Start: RF crossed behind LF, T turned out (Close Opp. Normal Hold)\nFinish: RF fwd and slightly across the body (R Side Opp. Normal Hold)"},
            {"CROSS BASIC",                 "2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd, T turned out (Close Opp. Normal Hold)\nFinish: RF to side (Close Opp. Normal Hold)"},
            {"CROSS BASIC WITH TURN",       "2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd, T turned out (Close Opp. Normal Hold)\nFinish: RF to side (Close Opp. Normal Hold)"},
            {"CROSS BASIC TO OPEN OPP. POS","2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd, T turned out (Close Opp. Normal Hold)\nFinish: RF to side (Open Opp. LH to RH)"},
            {"CHANGING FEET SIMPLE FOOT CHANGE","2 3",
                                                    "Start: LF fwd and across body (Open Opp. w/o Hold)\nFinish: Weight on RF (R Side Same, w/o Hold)"},
            {"CHANGING FEET CHASSE TO R SIDE LINK","2 3 4&1",
                                                    "Start: LF in place (R Diag. Opp. LH to RH)\nFinish: RF to side (R Side Same, w/o Hold)"},
            {"LOCK TO R SIDE LINK",         "2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd and slightly across the body(R Side Opp. w/o Hold)\nFinish: RF to side (R Side Same, w/o Hold)"},
            {"LINK TO OPEN OPP. POS.",      "2 3 4&1 2 3 4&1",
                                                    "Start: RF bwd (R Side Same, w/o Hold)\nFinish: RF fwd (Open Opp. LH to RH)"},
            {"SPLIT CUBAN BREAK TO R",      "2&3 (or 4&1)",
                                                    "Start: LF fwd and across body, T turned out (L Side Same, LH to RH)\nFinish: LF to side (Open Opp. LH to RH)"},
            {"SPLIT CUBAN BREAK TO L",      "2&3 (or 4&1)",
                                                    "Start: RF fwd and across body, T turned out(R Side Same, RH to LH)\nFinish: RF to side (Open Opp. RH to LH)"},
            {"CUBAN BREAKS TO R",           "2& 3& 4&1",
                                                    "Start: LF fwd and across body, T turned out (L Side Same, LH to RH)\nFinish: LF to side (Open Opp. LH to RH)"},
            {"CUBAN BREAKS TO L",           "2& 3& 4&1",
                                                    "Start: RF fwd and across body, T turned out (R Side Same, RH to LH)\nFinish: RF to side (Open Opp. RH to LH)"},
            {"CLOSE HIP TWIST SPIRAL",      "2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd, T turned out (Back R Diag. Same, Normal Hold)\nFinish: RF to side (Open Opp. LH to RH)"},
            {"OPEN HIP TWIST SPIRAL",       "2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd, T turned out (Open Opp. LH to RH)\nFinish: Weight on RF (Open Opp. LH to RH)"},
            {"TURKISH TOWEL",               "2 3 4&.1 2 3 4&1 2 3 4&.1 2 3 4&1 2 3 4&.1 2 3 4&1",
                                                    "Start: LF fwd, T turned Out (Open Opp. RH to RH)\nFinish: RF fwd (Open Opp. LH to RH)"},
            {"SWEETHEART",                  "2 3 4&1 2 3 4&1 2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd, T turned out (Open Opp. RH to RH)\nFinish: RF to side and slightly fwd (Close Opp. Normal Hold)"},
            {"FOLLOW MY LEADER",            "2 3 4&1 2 3 4&1 2 3 4&1 (&)2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd (Open Opp. w/o Hold)\nFinish: RF fwd (Open Opp. LH to RH)"},
            {"SYNCOPATED OPEN HIP TWIST",   "2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd, T turned out (Open Opp. LH to RH)\nFinish: RF to side (Fan L Angle, LH to RH)"},
            {"CURL",                        "2 3 4&1 2 3 4&1",
                                                    "Start: LF fwd.,T turned Out (Open Opp. LH to RH)\nFinish: RF to side (Fan L Angle, LH to RH)"},
            {"ROPE SPINNING",               "2 3 4&1 2 3 4&1",
                                                    "Start: LF to side (R Back Diag L Angle. RH to LH)\nFinish: LF fwd (R Diag. Opp. Normal Hold)"},
            {"OVERTURNED LOCK ENDING",      "4&1",
                                                    "Start: RF fwd (Open Same, LH to RH)\nFinish: RF fwd (Open Same, LH to RH)"},
            {"CONTINUOUS OVERTURNED LOCK",  "2 (&)3& 4&1",
                                                    "Start: LF fwd (Open Opp. LH to RH)\nFinish: RF fwd (Close Same, LH to RH)"},
            {"SWIVEL FROM OVERTURNED LOCK", "2 3 4&1",
                                                    "Start: LF fwd, T turned out (Open Same, LH to RH)\nFinish: LF bwd (Open Opp. LH to RH)"},
            {"SWIVEL HIP TWIST",            "2.3 4&1 ",
                                                    "Start: RF in place (L Diag.R Angle, Normal Hold)\nFinish: LF to side (Close Opp. Normal Hold)"},
            {"SWIVELS",                     "2 3 4&1",
                                                    "Start: RF in place (L Diag.R Angle, Normal Hold)\nFinish: RF to side (Fan L Angle, LH to RH)"},
            {"WALKS AND WHISKS",            "2 3 4&1 2&3 4&1",
                                                    "Start: LF fwd (L side Same, w/o Hold)\nFinish: LF to side and slightly fwd (Open Opp. LH to RH)"},
            {"CHANGING FEET LINK TO FAN L Angle",
                                            "2&3 41 2 3(&) 4&1",
                                                    "Start: LF Closed to RF (R Diag. Same, w/o Hold)\nFinish: RF to side (Fan L Angle, LH to RH)"},
            {"CHANGING FEET SYNCOPATED R SIDE LINK",
                                            "2 3 4&1 2&3 (4)&1 ",
                                                    "Start: LF fwd, T turned out (Open Opp. LH to RH)\nFinish: RF to side (R Side Same, w/o Hold)"}
};
}
