package com.olklein.choreo.syllabus;

/**
 * Created by olklein on 24/10/2017.
 */

public class jive {
    public static final String[][] FIGURESTEMPOLIST = {
            {"BASIC IN PLACE",                      "QQ QaQ QaQ",
                    "Start: LF in place (Close Opp., Normal Hold)\nFinish: RF to side (Close Opp., Normal Hold)"},
            {"BASIC IN FALLAWAY",                   "QQ QaQ QaQ",
                    "Start: LF bwd (Close Fallaway, Prom Hold)\nFinish: RF to side (Close Opp., Normal Hold)"},
            {"CHANGE OF PLACE FROM RIGHT TO LEFT",  "QQ QaQ QaQ",
                    "Start: LF bwd (Close Fallaway, Prom Hold)\nFinish: RF Fwd and slightly to side (Close Opp., LH to RH Hold)"},
            {"CHANGE OF PLACE FROM LEFT TO RIGHT",  "QQ QaQ QaQ",
                    "Start: LF bwd (Open Opp., LH to RH Hold)\nFinish: RF fwd (Open Opp., LH to RH Hold)"},
            {"AMERICAN SPIN",                       "QQ QaQ QaQ",
                    "Start: LF bwd (Open Opp., RH to RH Hold)\nFinish: RF Diag. fwd (Open Opp., LH to RH Hold)"},
            {"CHANGE OF PLACE BEHIND THE BACK",     "QQ QaQ QaQ",
                    "Start: LF bwd (Open Opp., LH to RH Hold)\nFinish: RF to side (Open Opp., LH to RH Hold)"},
            {"LINK",                                "QQ QaQ QaQ",
                    "Start: LF bwd (Open Opp., LH to RH Hold)\nFinish: RF to side (Close Opp., Normal Hold)"},
            {"WHIP",                                "QQ QaQ",
                    "Start: RF crossed behind LF (Open Opp., Normal Hold)\nFinish: RF to side (Close Opp., Normal Hold)"},
            {"PROMENADE WALKS - SLOW",              "QQ QaQ QaQ",
                    "Start: LF bwd (Close Fallaway, Prom Hold)\nFinish: RF fwd (Close Opp., Normal Hold)"},
            {"PROMENADE WALKS - QUICK",             "QQ QQQQ",
                    "Start: LF bwd (Close Fallaway, Prom Hold)\nFinish: RF closed to LF, weight on LF (Close Prom, Normal Hold)"},
            {"FALLAWAY THROWAWAY",                  "QQ QaQ QaQ",
                    "Start: LF bwd (Close Fallaway, Prom Hold)\nFinish: RF fwd and slightly to side (Open Opp., LH to RH Hold)"},
            {"CHANGE OF PLACE FROM RIGHT TO LEFT WITH DOUBLE SPIN", "QQ QaQ QaQ",
                    "Start: LF bwd (Close Fallaway, Prom Hold)\nFinish: RF fwd and slightly to side (Open Opp., LH to RH Hold)"},
            {"OVERTURNED CHANGE OF PLACE FROM LEFT TO RIGHT",       "QQ QaQ QaQ",
                    "Start: LF bwd (Open Opp., LH to RH Hold)\nFinish: RF fwd (Open Same, LH to RH Hold)"},
            {"DOUBLE CROSS WHIP",                   "QQQQ QaQ",
                    "Start: RF crossed behind LF (Close Opp., Normal Hold)\nFinish: RF to side (Close Opp., Normal Hold)"},
            {"THROWAWAY WHIP",                      "QQ QaQ",
                    "Start: RF crossed behind LF (Close Opp., Normal Hold)\nFinish: RF to side (Open Opp., LH to RH Hold)"},
            {"REVERSE WHIP",                        "QQ QaQ QQ QaQ",
                    "Start: LF bwd (Close Fallaway, Prom Hold)\nFinish: RF to side (Close Opp., Normal Hold)"},
            {"CURLY WHIP",                          "QQ QaQ",
                    "Start: LF bwd (Open Opp., LH to RH Hold)\nFinish: LF to side (Close Opp., Normal Hold)"},
            {"OVERTURNED FALLAWAY THROWAWAY",       "QQ QaQ QaQ",
                    "Start: LF bwd (Close Fallaway, Prom Hold)\nFinish: RF fwd and across body (Open Opp., LH to RH Hold)"},
            {"STOP AND GO",                         "QQ QaQ QQ QaQ",
                    "Start: LF bwd (Open Opp., LH to RH Hold)\nFinish: RF diag. fwd (Open Opp., LH to RH Hold)"},
            {"HIP BUMP",                            "QQQQ QaQ",
                    "Start: LF bwd (Open Opp., LH to RH Hold)\nFinish: RF diag., fwd to end RF bwd (Open Opp., LH to RH Hold)"},
            {"WINDMILL",                            "QQ QaQ QaQ",
                    "Start: LF bwd (Open Opp., LH to RH and RH to LH Hold)\nFinish: RF to side and slightly fwd (Open Opp., LH to RH and RH to LH Hold)"},
            {"MOOCH",                               "QQQQ QQQQ QaQ QQQQ QQQQ QaQ",
                    "Start: LF bwd (Close Opp., Normal Hold)\nFinish: RF to side (Close Opp., Normal Hold)"},
            {"SPANISH ARMS",                        "QQ QaQ QaQ QQ QaQ QaQ",
                    "Start: LF bwd (Open Opp., LH to RH and RH to LH Hold)\nFinish: RF slightly fwd (Open Opp., LH to RH Hold)"},
            {"CHICKEN WALKS",                       "SSSS",
                    "Start: LF slightly bwd, weight on RF (Open Opp., LH to RH Hold)\nFinish: RF slightly bwd, weight on LF (Close Opp., LH to RH Hold)"},
            {"ROLLING OFF THE ARM",                 "QQ QaQ QQ QaQ",
                    "Start: LF bwd (Open Opp., RH to RH Hold)\nFinish: RF diag.fwd (Open Opp., RH to RH Hold)"},
            {"SIMPLE SPIN",                         "QQ",
                    "Start: LF closed to RF (Open Opp., Release Hand Hold)\nFinish: RF closed to LF (Open Opp., LH to RH Hold)"},
            {"ROCK TO SIMPLE SPIN",                 "QQQQ",
                    "Start: LF bwd (Open Opp., LH to RH Hold)\nFinish: RF closes to LF (Open Opp., LH to RH Hold)"},
            {"FLICKS INTO BREAK",                   "QQQQ QQQQ aQ(QQ)aQ",
                    "Start: LF bwd (Open Opp., LH to RH and RH to LH Hold)\nFinish: RF fwd and across body (Open Prom, LH to RH and RH to LH Hold)"},
            {"TOE HEEL SWIVELS",                    "QQ QQS QQS",
                    "Start: LF bwd (Open Opp., LH to RH and RH to LH Hold)\nFinish: RF fwd and across body (Open Prom, LH to RH and RH to LH Hold)"},
            {"SUGAR PUSH",                          "QaQ QQ QaQ",
                    "Start: Position Held, Weight on RF (Open Opp., LH to RH Hold)\nFinish: RF fwd and slightly across body (Open Opp., LH to RH Hold)"},
            {"MIAMI SPECIAL",                       "QQ QaQ QaQ",
                    "Start: LF bwd (Open Opp., RH to RH Hold)\nFinish: RF to side (Open Opp., LH to RH Hold)"},
            {"SHOULDER SPIN",                       "QQ QaQ QaQ QQ QaQ QaQ",
                    "Start: LF bwd (Open Opp., RH to RH Hold)\nFinish: RF slightly bwd (Open Opp., LH to RH Hold)"},
            {"CHUGGING",                            "QQ QaQ QaQ QaQ QaQ QaQ QaQ",
                    "Start: LF bwd (Open Opp., RH to RH Hold)\nFinish: RF diag. Fwd (Open Opp., LH to RH Hold)"},
            {"A CHUGGING",                          "QQ QaQ QaQ QaQ QaQ QaQ QaQ",
                    "Start: LF bwd (Open Opp., RH to RH Hold)\nFinish: RF to side (Open Opp., LH to RH Hold)"},
            {"CATAPULT",                            "QQ QaQ QaQ QQ QaQ QaQ",
                    "Start: LF bwd (Open Opp., RH to RH Hold)\nFinish: RF diag.fwd. (Open Opp., LH to RH Hold)"},
            {"BALL CHANGE",                         "QaQ",
                    "Start: LF pointed diag. fwd w/o wt (Open Opp., LH to RH Hold)\nFinish: RF in place (Open Opp., LH to RH Hold)"},
            {"STALKING WALKS, FLICKS AND BREAK",    "QQQQ QQQQ QQQQ QQQQ Q(Q Q)aQ",
                    "Start: LF bwd (Open Opp., LH to RH and RH to LH hold)\nFinish: Weight on RF (Open Prom, LH to RH and RH to LH Hold)"},
    };
}
