package com.olklein.choreo.syllabus;

/**
 * Created by olklein on 24/10/2017.
 */

public class rumba {
    public static final String[][] FIGURESTEMPOLIST = {
            {"CLOSE BASIC MOVEMENT",    "2 3 4.1 2 3 4.1",
                                            "Start: LF fwd (Close Opp. Normal Hold)<br>Finish: RF to side (Close Opp. Normal Hold)"},
            {"OPEN BASIC MOVEMENT",     "2 3 4.1 2 3 4.1",
                                            "Start: LF fwd (Open Opp. LH to RH hold)\nFinish: RF fwd (Open Opp. LH TO RH hold)"},
            {"NEW YORK TO R",           "2 3 4.1",
                                            "Start: LF fwd (Left Side Same Pos. LH to RH)\nFinish: LF to side (Open Opp. LH to RH)"},
            {"NEW YORK TO L",           "2 3 4.1",
                                            "Start: RF fwd (Right Side Same Pos. RH to LH)\nFinish: RF to side (Open Opp. RH to LH)"},
            {"HAND TO HAND TO R",       "2 3 4.1",
                                            "Start: RF bwd (Left Side Same Pos. LH to RH)\nFinish: RF fwd (Open Opp. LH to RH)"},
            {"HAND TO HAND TO L",       "2 3 4.1",
                                            "Start: LF bwd (Right Side Same Pos. RH to LH)\nFinish: LF fwd (Open Opp. RH to LH)"},
            {"SPOT TURN TO R",          "2 3 4.1",
                                            "Start: LF fwd and slightly across (Left Side Same Pos. no hold)\nFinish: LF to side (Open Opp. LH to RH)"},
            {"SPOT TURN TO L",          "2 3 4.1",
                                            "Start: RF fwd and slightly across (Right Side Same Pos. no hold)\nFinish: RF to side (Open Opp. RH to LH)"},
            {"UNDERARM TURN TURNING R", "2 3 4.1",
                                            "Start: RF bwd (Left Diag. R Angle Pos. LH to RH)\nFinish: RF to side (Close Opp. Normal Hold)"},
            {"UNDERARM TURN TURNING L", "2 3 4.1",
                                            "Start: LF fwd and slightly across (Left Diag. Same, LH to RH)\nFinish: LF to side (Open Opp. LH to RH)"},
            {"SIDE WALKS AND CUCARACHAS",   "2 3 4.1 2 3 4.1 2 3 4.1 2 3 4.1",
                                            "Start: LF to side (Close Opp. Normal hold)\nFinish: RF closed to LF (Close Opp. Normal hold)"},
            {"FAN",                     "2 3 4.1",
                                            "Start: RF to bwd (L Diag. Opp. RH releases hold)\nFinish: RF to side (Fan L Angle, LH to RH)"},
            {"OPEN HIP TWIST",          "2 3 4.1 2 3 4.1",
                                            "Start: LF fwd (Open Opp. LH to RH)\nFinish: RF to side (Fan L Angle, LH to RH)"},
            {"OPEN HIP TWIST FINISHED TO SIDE","2 3 4.1 2 3 4.1",
                                            "Start: LF fwd (Open Opp. LH to RH)\nFinish: RF to side (Open Opp. LH to RH)"},
            {"HOCKEY STICK",            "2 3 4.1 2 3 4.1",
                                            "Start: LF fwd (Fan L Angle, LH to RH)\nFinish: RF fwd (Open Opp. LH to RH)"},
            {"HOCKEY STICK FINISHED TO SIDE","2 3 4.1 2 3 4.1",
                                            "Start: LF fwd (Fan L Angle, LH to RH)\nFinish: RF to side (Open Opp. LH to RH)"},
            {"OPENING OUT" ,            "2 3 4.1 2 3 4.1",
                                            "Start: LF to side (R Diag. R Angle, Release LH hold)\nFinish: RF closed to LF (Close Opp. RH to Lady’s L shoulder blade)"},
            {"SHOULDER TO SHOULDER",    "2 3 4.1 2 3 4.1","Start: LF fwd (l Diag. Opp. w/o Hold)\nFinish: RF to side (Open Opp. w/o Hold)"},
            {"ALTERNATIVE BASIC MOVEMENT","2 3 4.1","Start: LF closed to RF (Ex. Open Opp. LH to RH)\nFinish: LF to side (Close Opp. Normal Hold)"},
            {"CLOSE HIP TWIST",         "2 3 4.1 2 3 4.1",
                                            "Start: LF fwd (Back R Diag same, Normal Hold)\nFinish: RF to side and slightly Fwd (Fan L Angle. LH to RH)"},
            {"CLOSE HIP TWIST FINISHED TO SIDE","2 3 4.1 2 3 4.1",
                                            "Start: LF fwd (Back R Diag. same, Normal Hold)\nFinish: RF to side (Open Opp. LH to RH)"},
            {"ALEMANA",                 "2 3 4.1 2 3 4.1",
                                            "Start: LF fwd (Fan L Angle, LH to RH)\nFinish: RF fwd and slightly across body (R Diag. Opp. Normal Hold)"},
            {"ALEMANA FINISHED TO SIDE","2 3 4.1 2 3 4.1",
                                            "Start: LF fwd (Fan L Angle, LH to RH)\nFinish: RF to side (Open Opp. LH to RH)"},
            {"PROGRESSIVE FORWARD WALKS","2 3 4.1 2 3 4.1 2 3 4.1",
                                            "Start: RF fwd (R Diag. Same, RH on Lady’s R shoulder)\nFinish: RF fwd (Open Opp. LH to RH)"},
            {"PROGRESSIVE FORWARD WALKS TO FAN","2 3 4.1 2 3 4.1 2 3 4.1",
                                            "Start: RF fwd (R Diag. Same, RH on Lady’s R shoulder)\nFinish: Weight on RF (Fan L Angle, LH to RH)"},
            {"AIDA","2 3 4.1 2& 3 4.1 2 3 4.1",
                                            "Start: RF fwd(R Side. Same, RH to LH)\nFinish: RF to side (Open Opp. LH to RH)"},
            {"CONTINUOUS HIP TWIST","2 3 4.1 2 3 4.1",
                                            "Start: LF fwd, T turned out (Back R Diag. same, Normal Hold)\nFinish: RF fwd and slightly across body (R Diag. Opp. Normal Hold)"},
            {"CUBAN ROCKS",             "2 3 4.1 or 2&3 4.1",
                                            "Start and\nFinish: RF or LF depending on the preceding figure"},
            {"FENCING TO SPIN",         "2 3 4.1 2 3 4.1 2.3 4.1",
                                            "Start: LF fwd (Fan L Angle, LH to RH)\nFinish: RF to side (Open Opp. Normal Hold or w/o hold)"},
            {"CONTINUOUS CIRCULAR HIP TWIST","2 3 4.1 2 3 4.1 2 3 4.1 2 3 4.1",
                                            "Start: LF fwd (Back R Diag. same, RH to RH or Normal Hold)\nFinish: RF to side (Fan L Angle., LH to RH)"},
            {"SYNCOPATED OPEN HIP TWIST","2 3 4.1 2& 3 4.1",
                                            "Start: LF fwd (Open Opp. LH to RH)\nFinish: RF to side (Fan L Angle., LH to RH)"},
            {"NATURAL TOP",             "2 3 4.1 2 3 4.1 2 3 4.1",
                                            "Start: RF crossed behind LF (Close Opp. Normal Hold)\nFinish: RF fwd and slightly across body OP (R Diag. Opp. Normal Hold)"},
            {"REVERSE TOP",             "2 3 4.1 2 3 4.1",
                                            "Start: LF in place (Close Opp. Normal Hold)\nFinish: RF to side (Close. Opp. Normal Hold)"},
            {"CURL",                    "2 3 4.1 2 3 4.1",
                                            "Start: LF fwd (Open Opp. LH to RH)\nFinish: RF to side (Fan L Angle, LH to RH)"},
            {"CURL FINISHED TO SIDE",   "2 3 4.1 2 3 4.1",
                                            "Start: LF fwd (Open Opp. LH to RH)\nFinish: RF to side (Open Opp. LH to RH)"},
            {"SPIRAL",                  "2 3 4.1 2 3 4.1",
                                            "Start: LF to side (Back R Diag. Same, Normal Hold)\nFinish: RF fwd (Open Opp. LH to RH)"},
            {"SPIRAL FINISHED TO SIDE", "2 3 4.1 2 3 4.1",
                                            "Start: LF to side (Back R Diag. Same, Normal Hold)\nFinish: RF to side (Open Opp. LH to RH)"},
            {"SPIRAL TO FAN",           "2 3 4.1 2 3 4.1",
                                            "Start: LF to side (Back R Diag. Same, Normal Hold)\nFinish: RF to side (Fan L Angle., LH to RH)"},
            {"THREE ALEMANAS",          "2 3 4.1 2 3 4.1 2 3 4.1 2 3 4.1",
                                            "Start: LF fwd (Fan L Angle, LH to RH)\nFinish: RF fwd and slightly across body (R Diag. Opp.., Normal Hold)"},
            {"SLIDING DOORS",           "2 3 4.1 2 3 4.1 2 3 4.1 2 3 4.1",
                                            "Start: LF fwd (Fan L Angle, LH to RH)\nFinish: RF closed to LF (R Side Same., RH on Lady’s R shoulder) "},
            {"ADVANCED SLIDING DOORS",  "2 3 4.1 2 3 4.1",
                                            "Start: LF fwd (Back R Diag. Same, w/o Hold)\nFinish: RF fwd and slightly across body (R Diag. Opp. w/o Hold)"},
            {"THREE THREES",            "2 3 4.1 2 3 4.1 2 3 4.1 2 3 4.1",
                                            "Start: LF fwd (Open Opp. LH to RH)\nFinish: RF fwd (Open Opp.., LH to RH)"},
            {"THREE THREES TO FAN",     "2 3 4.1 2 3 4.1 2 3 4.1 2 3 4.1",
                                            "Start: LF fwd (Open Opp. LH to RH)\nFinish: RF to side (Fan L Angle, LH to RH)"},
            {"ROPE SPINNING",           "2 3 4.1 2 3 4.1",
                                            "Start: LF to side (R Diag. Opp. LH to RH)\nFinish: RF closed to LF (Close Opp. LH to RH)"},
            {"SWIVELS",                 "2 3 4.1 2 3 4.1 2 3 4.",
                                            "Start: RF to side (L Diag. R Angle., Normal Hold)\nFinish: RF to side (Fan L Angle, LH to RH)"},
            {"OVERTURNED BASIC",        "2 3 4.1 2 3 4.",
                                            "Start: LF fwd (Ext. Open Opp. LH to RH)\nFinish: LF bwd (Open Opp. LH to RH)"}

    };

}
